---

# plugins: [flowtype]

env:
  node: true
  jest: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 2017
  sourceType: module

extends:
  - 'airbnb-base'
  - plugin:import/errors
  - plugin:import/warnings
<<<<<<< HEAD

rules:
  no-console: 0
=======
>>>>>>> aa39fc60138c1e2c50f5096d67ee524e0733b081
